# Generated by Django 5.0.3 on 2024-03-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(default='user', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('mobile', models.PositiveBigIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
