# Generated by Django 5.0.2 on 2024-03-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookevent',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
